### ISSUE TITLE
Setting Media.AlwaysIncludeServerUrl to true breaks images that use synthesis

### ISSUE THREAD

**Issue by robertpateii** [kamsar/Synthesis#13]
I set Media.AlwaysIncludeServerUrl to true in the Web.config and the images that rely on synthesis now 404.

They look like this below. Note the extra / at the beginning.
`<img src="/http://www.lifesize.com/~/media/Images/New%20Images/Home/billboard.ashx">`

Synthesis [tries to prevent this behavior by checking AlwaysIncludeServerUrl](https://github.com/kamsar/Synthesis/blob/master/Source/Synthesis/Utility/FieldUtility.cs#L21), but we have that set to false because we only want the full URL for media items.

@jeremyclifton is working on a fix now and will reference this ticket in his pull request.

**Comment by kamsar** [comment]
#14 has been merged
