### ISSUE TITLE
If MaxBackupCopies = 0 i want no create backups

### ISSUE THREAD

**Issue by patocl** [kamsar/Synthesis#28]
I will like that synthesis not create backup if the flag MaxBackupCopies on synthesys.config is 0 (zero)
When the MaxBackupCopies = 0 the synthesis get a infinite loop

on file located in Synthesis\Generation\CodeDom\CodeDomGenerator.cs
for the method WriteFileWithBackups i will like do this change

			if (File.Exists(path)) // existing version present; make backups as necessary
			{
				uint maxBackups = _parameters.MaxBackupCopies;
			    if (maxBackups == 0) return;

**Comment by AlexKasaku** [comment]
Just encountered this too, we don't need the backups and set this to zero, which created this infinite loop.

**Comment by kamsar** [comment]
This will be fixed in the next release.

**Comment by patocl** [comment]
Thanks, I saw your presentation on Sugcon 2016, very good, thanks alot nice
and well xplained all!!!

**Comment by kamsar** [comment]
Fixed in 8.2.1
