### ISSUE TITLE
Synthesis and SOLR - ArgumentNullException

### ISSUE THREAD

**Issue by zimpy** [kamsar/Synthesis#34]
When requesting /synthesis.aspx it throws this exception. Unfortunately I don't have some steps to reproduce:

`[ArgumentNullException: Value cannot be null.
Parameter name: fieldTypeName]
   Sitecore.Diagnostics.Assert.ArgumentNotNull(Object argument, String argumentName) +63
   Sitecore.ContentSearch.SolrProvider.SolrFieldMap.GetFieldConfigurationByFieldTypeName(String fieldTypeName) +40
   Sitecore.ContentSearch.SolrProvider.SolrFieldNameTranslator.ProcessFieldName(String fieldName, Type returnType, CultureInfo culture, String returnTypeString, Boolean aggressiveResolver) +1319
   Sitecore.ContentSearch.SolrProvider.SolrFieldNameTranslator.GetIndexFieldName(String fieldName) +31
   Synthesis.Generation.MetadataGenerator.GenerateMetadata() +868
   Synthesis.SynthesisHelper.ExecMetadataWithAutoFriending(IEnumerable`1 configurations, Action`2 processAction) +467
   Synthesis.SynthesisHelper.CheckSyncAll() +181
   Synthesis.ControlPanel.ControlPanelPipelineProcessor.CreateSyncSummary() +110`

**Comment by zimpy** [comment]
It seems like this happened because i didn't have any fields on my template. It only had some base templates. When i added a field directly on it, it worked.

**Comment by kamsar** [comment]
As a longer term enhancement, Synthesis really should modularize the content search stuff out of the core and into Lucene and Solr specific packages. Or maybe a shorter term one, if I can find the time (what's spare time again?)

**Comment by kamsar** [comment]
This isn't a complete fix but https://github.com/kamsar/Synthesis/commit/306aac569cea3efd4c9667c14c18d6110f6fbca8 makes it not error (and generated no `[IndexField]` when the Solr name translator fails), as well as the option to disable content search integration entirely. This is in 8.2.2-RC01 on NuGet.

**Comment by kamsar** [comment]
This is fixed in 8.2.2 with an improved method from RC01
