### ISSUE TITLE
Could not find a part of the path

### ISSUE THREAD

**Issue by rolek** [kamsar/Synthesis#35]
System.IO.DirectoryNotFoundException: Could not find a part of the path.. blah blah.

Shouldn't it create missing directories ?
One of the directories in the path is missing. Exception happens.

**Comment by kamsar** [comment]
Sorry but this issue report needs some additional detail to be actionable. Where did you get the error? What were you doing at the time?

**Comment by rolek** [comment]
My issue description was a little cryptic. Sorry about that. I was going to edit it but forgot.

Synthesis configuration contains bunch of paths to store generated models. For example:

C:\Projects\MyAwesomeProject\Subproject\Models\<filenamehere>

Now, in this directory structure, "Models" directory does not exist, because I am using modular architecture and I want the models to always be in the directory for each project (lets assume 20 of them).

Error happens when you go to Synthesis page and regenerate model.

**Comment by kamsar** [comment]
This is fixed in 8.2.2
