### ISSUE TITLE
Get a synthesis type via template

### ISSUE THREAD

**Issue by sergey-solomentsev-nemetos** [kamsar/Synthesis#39]
Hi @kamsar ,
I've got a question about Synthesis: if there is a way to get a synthesis type via a template?

Being more concrete, I want to use a method which looks like this:

`public Type GetSynthesisTypeBy(ID templateId) { ... }`

And so having the ISampleItemItem ("/sitecore/templates/Sample/Sample Item" from out-of-the-box Sitecore) I want to get its type like this:
`var template = GetSynthesisTypeBy(new ID("{76036F5E-CBCE-46D1-AF0A-4143F9B557AA}")); // typeof(ISampleItemItem)`

**Comment by kamsar** [comment]
Yes, indirectly. https://github.com/kamsar/Synthesis/blob/Sitecore-8.1/Source/Synthesis/Configuration/ProviderResolver.cs#L41, which will return a https://github.com/kamsar/Synthesis/blob/Sitecore-8.1/Source/Synthesis/Initializers/ITemplateInitializer.cs

This does not expose the type directly. But if you create an initializer from search using an empty dictionary, the type of the result will be what you're after.
