### ISSUE TITLE
GetResults() Issue in ContentSearch

### ISSUE THREAD

**Issue by scottmulligan** [kamsar/Synthesis#4]
Hey there. I hope this is not a stupid question but I have been unable to use the GetResults() method at the end of a query when using GetSynthesisQueryable. Doing so returns a System.NullReferenceException.

For example:

using (var context = ContentSearchManager.GetIndex("sitecore_web_index").CreateSearchContext())
            {
                var results = context.GetSynthesisQueryable<IResourceItem>()
                    .GetResults();
            }

I am successfully able to use other methods like GetFacets() and ToList(). Hopefully I am just missing something but let me know if you have any ideas.

I am using the latest version of Sitecore 7.1 (130926)

**Comment by kamsar** [comment]
I'm afraid this issue is also present in Sitecore 8 RTM.

**Comment by Gobiner** [comment]
I am also running into this issue.
