### ISSUE TITLE
Feature Request Support derived templates in As<> strongly typed extension

### ISSUE THREAD

**Issue by WizX20** [kamsar/Synthesis#40]
**Feature request**

Currently the item extensions only look for the direct TemplateId of the item, and not at the base templates (or deeper): Synthesis.ItemExtensions.As<_Template>(bool derived)

It would be nice if the Synthesis extensions look for derived templates. Example (from habitat):
`private static bool IsDerived(this Item item, Item templateItem)
    {
      if (item == null)
      {
        return false;
      }

      if (templateItem == null)
      {
        return false;
      }

      var itemTemplate = TemplateManager.GetTemplate(item);
      return itemTemplate != null && (itemTemplate.ID == templateItem.ID || itemTemplate.DescendsFrom(templateItem.ID));
    }`

Sitecore version: 8.2.160729
Synthesis version: 8.2.2-RC02

**Comment by kamsar** [comment]
The base templates are pulled by interfaces and are considered. The most
specific concrete type is returned but will implement all interfaces of
base templates.

**Comment by WizX20** [comment]
I'll try and sketch the situation using Habitat, please correct me if I'm doing anything out of the ordinary.

- We have a feature, which contains some templates, eg:
 - /sitecore/templates/Feature/Navigation/_NavigationLink (has a general link field called Link)
- In the project part we bring the stuff together, so we have a template there that has the _NavigationLink as a base template:
 - /sitecore/templates/Project/MySite/Content Types/Navigation/Navigation Link

- In the Habitat solution I create a new feature, called navigation. For Synthesis I use a FeatureModelRegistration.cs:
`protected override string NamespaceTemplatePathRoot => $"/sitecore/templates/Feature/Navigation";`
`protected override string RootGeneratedNamespace => "MySite.Feature.Navigation.Models";`
This will create my Model class (called NavigationModel.cs) and will add a _NavigationLink class.

- Finally I will create a View that will loop through the navigation-links from some site-tree I've created.
`@foreach (var item in Model.Items) { ...`
Now I want the item as a strongly typed one, so I do:
`var navigationLink = item.As<_NavigationLink>();`
This will return **null**. Because the extension uses the item's templateId to look for configured templates in Synthesis.ItemExtensions:
`ITemplateInitializer initializer = ProviderResolver.FindGlobalInitializer(item.TemplateID);`

It does not exist, because I have not added the project-template part to the configuration, and, I don't want to because this will create dependency in my feature to the (MyWebsite) project. This is not allowed according to the Helix architecture.

A way to get this to work would perhaps be doing something like this:
`public static TTemplate As<TTemplate>(this Item item) where TTemplate : class, IStandardTemplateItem
    {`
      `// we need the Sitecore item`
      `if (item == null)
      {
        return null;
      }`

      `// get an instance of the template we want to convert to
      var templateItem = (TTemplate)Activator.CreateInstance(typeof(TTemplate), new object[] { item });`

      `// check if it's of the correct template type
      if (!item.IsDerived(templateItem.TemplateId))
      {
        throw new ArgumentException(
          $"{nameof(item)} is not derived from the template {templateItem.TemplateId}!");
      }`

      `return templateItem;
    }`

But then we will use reflection, and that's slow. I'm not sure if there is any other way to do this.

**Comment by kamsar** [comment]
Template inheritance should also follow Helix principles, and to really use Synthesis with Habitat you'd need to add models to most if not all of the features (internally I'm using this in a Helix-like architecture).

So if your website for example is inheriting a feature template, both the website and the feature should have model registrations, and it will naturally be required to reference the feature's project from the website as a result of that dependency. The models will automatically refer to each other in 8.2.1 and later due to 'auto-friending'.
