### ISSUE TITLE
Feature request: Able to pass model as argument in MVC Helpers

### ISSUE THREAD

**Issue by WizX20** [kamsar/Synthesis#41]
**Feature request**

Create an overloadable/extra argument for all the Synthesis.Mvc.Helpers. In some cases it can be useful if you can pass a different model other then the one currently in the viewdata. Now they all do:
`ITextField textField = selector(helper.ViewData.Model);`

Sitecore version: 8.2.160729
Synthesis version: 8.2.2-RC02

**Comment by kamsar** [comment]
I use `@Html.TextFor(m => otherVariable.Field)` for this. Works fine.
