### ISSUE TITLE
Better support for overriding ConfigurationTemplateInputProvider

### ISSUE THREAD

**Issue by JensMikkelsen** [kamsar/Synthesis#45]
Hey Kamsar,

Great work with the module.

I am trying to override the ConfigurationTemplateInputProvider, so that an exception isn't thrown if the root of the template root item isn't found. E.g. I might have a root saying /sitecore/templates/feature.

When I first install Sitecore this item isn't present, and I get the error Synthesis Config Error: The path /sitecore/Templates/Feature did not map to a valid item

And I am unable to sync TDS in because of this. So I want to ignore it, if the item isn't present. 

To do this I try and override ConfigurationTemplateInputProvider. At first I just want to override ResolveSpecToItems(string input, IEnumerable<Item> possibilities), but this is private. Then I think I can override RefreshSpecTargets() but this isn't virtual. Then I want to override CreateTemplateList(), but I cannot access the private properties _templates, which makes it a little harder (all though I can create my own, but it could be used elsewhere).

Is it possible to make the method protected virtual and/or the properties protected?

Thanks
Jens

**Comment by kamsar** [comment]
This is fixed in Synthesis 8.2.5 on NuGet now.
