### ISSUE TITLE
ITemplateInputProvider uses specific class

### ISSUE THREAD

**Issue by JensMikkelsen** [kamsar/Synthesis#47]
Hi Kam,

I know I am the annoying guy :)

Anyway in SynthesisConfigurationRegistration the method LoadTemplateInputProviderFromConfig has a hardcoded reference to ConfigurationTemplateInputProvider. This should be loaded through the configurationation file. Otherwise it is not possible to replace the ITemplateInputProvider. 

Cheers
Jens

**Comment by kamsar** [comment]
Totally necro reply but this is not quite the case; each configuration may choose to have its own template input provider (they are separate entities), and thus loading the global default from config doesn't make sense.

If a specific config wants to override it, it can override `LoadTemplateInputProviderFromConfig()` itself and alter the loading code to use a different provider of its choice - configuration via code.

I'm working on some configuration changes that will also obsolete this and make it a lot simpler/more clear to handle configurations :)
