### ISSUE TITLE
Casting IStandardTemplateItem to the Actual Template (IItemReferenceListField issue)

### ISSUE THREAD

**Issue by ajgreenman** [kamsar/Synthesis#49]
I am using Sitecore 8.2 and Synthesis 8.2.5.

I have a content item that is using a Treelist field to grab images out of the content tree. Synthesis generates this field as an IItemReferenceListField. In the ModelRegistration class for this module, I add the Image system template (/sitecore/Templates/System/Media/Unversioned/Image).  My question is how do I get the images from this field strongly typed to that template (IImageItem).

This is what I've tried (in addition to a couple of similar variations)
`var model = RenderingContext.Current.ContextItem.As<I_ModelItem>();`
`var images = (IEnumerable<IImageItem>) model.Images.TargetItems.AsEnumerable(); `

When I try this, I get the following error: Unable to cast object of type 'System.Collections.ObjectModel.ReadOnlyCollection`1[Synthesis.IStandardTemplateItem]' to type 'System.Collections.Generic.IEnumerable`1[Company.Feature.Module.Models.System.Module.Unversioned.IImageItem]'.

**Comment by kamsar** [comment]
Pretty sure you can just use `Field.TargetItems.Cast<IImageItem>()`

**Comment by kamsar** [comment]
or `.OfType<IImageItem>()` if you wish to filter out anything not matching instead of throw

**Comment by ajgreenman** [comment]
Hey Kam,

Both of your suggestions worked great. In fact the actual problem was on our end, where we were getting Jpegs but not telling Synthesis to expect a Jpeg, thus the templates we're accurate. It's all fixed now. Thanks for your response!
