### ISSUE TITLE
Error on Web page load

### ISSUE THREAD

**Issue by unstab1e** [kamsar/Synthesis#55]
Kam,

My project is in github and I downloaded it to a different machine than I created it on. I have the same development environment (VS2015 Community) and the same Synthesis v8.2.5. However when I build the solution, deploy it and refresh the website I get the following error. What am I doing wrong?

Unable to cast object of type 'System.String' to type 'Synthesis.Templates.ITemplateInputProvider'.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'Synthesis.Templates.ITemplateInputProvider'.

Source Error: 

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace: 

[InvalidCastException: Unable to cast object of type 'System.String' to type 'Synthesis.Templates.ITemplateInputProvider'.]
   Synthesis.Configuration.ConfigurationProviderConfiguration.LoadTemplateInputProviderFromConfig() +45
   Synthesis.Configuration.ConfigurationProviderConfiguration.get_TemplateInputProvider() +108
   Synthesis.SynthesisHelper.ExecMetadataWithAutoFriending(IEnumerable`1 configurations, Action`2 processAction) +230
   Synthesis.SynthesisHelper.CheckSyncAll() +161
   Synthesis.Pipelines.Initialize.CheckModelSynchronization.DoLogSync() +45
   (Object , Object[] ) +71
   Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) +484
   Sitecore.Nexus.Web.HttpModule.Application_Start() +227
   Sitecore.Nexus.Web.HttpModule.Init(HttpApplication app) +673
   System.Web.HttpApplication.RegisterEventSubscriptionsWithIIS(IntPtr appContext, HttpContext context, MethodInfo[] handlers) +618
   System.Web.HttpApplication.InitSpecial(HttpApplicationState state, MethodInfo[] handlers, IntPtr appContext, HttpContext context) +172
   System.Web.HttpApplicationFactory.GetSpecialApplicationInstance(IntPtr appContext, HttpContext context) +402
   System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext) +343

[HttpException (0x80004005): Unable to cast object of type 'System.String' to type 'Synthesis.Templates.ITemplateInputProvider'.]
   System.Web.HttpRuntime.FirstRequestInit(HttpContext context) +539
   System.Web.HttpRuntime.EnsureFirstRequestInit(HttpContext context) +125
   System.Web.HttpRuntime.ProcessRequestNotificationPrivate(IIS7WorkerRequest wr, HttpContext context) +731

**Comment by kamsar** [comment]
Sounds like it's missing some configuration or assemblies.
