### ISSUE TITLE
In Synthesis 8.2.6, GetSynthesisQueryable method throws error when using SOLR

### ISSUE THREAD

**Issue by adkrishnamoorthy** [kamsar/Synthesis#59]
We are trying to use the GetSynthesisQueryable methods as below
context.GetSynthesisQueryable<IProductItem>(). We get the below error.
Type of context is IProviderSearchContext.
Exception Details: System.NotImplementedException: At this time Synthesis only supports Lucene indexes. This works with lucene index.
We expect GetSysthesisQueryable to work with SOLR.

Sitecore Version: 8.1 Update 1
Synthesis Version: 8.2.6
SOLR Version: 5.3.1

**Comment by kamsar** [comment]
Solr, as the message says, is not currently supported. There's a half done
PR to add it; you're welcome to pick it up and finish it if you need the
support.

**Comment by adkrishnamoorthy** [comment]
Hi, Do we have support for SOLR in latest version 8.2.6?

**Comment by blipson89** [comment]
@adkrishnamoorthy not yet. Please see the PR for #21
